name: 'Copy Secrets'
description: 'Copy secret information for server'
inputs:
  profile:
    description: 'profile which secret belong to'
    required: true
  oauth-secret:
    description: 'oauth secret file'
    required: true
  s3-secret:
    description: 's3 secret file'
    required: true
  fcm-secret:
    description: 'fcm secret file'
    required: true
  fcm-key:
    description: 'fcm key file'
    required: true
  fcm-key-path:
    description: 'fcm key file path'
    required: true
  fcm-key-file-name:
    description: 'fcm key file name'
    required: true
  dev-db-secret:
    description: 'development db secret file'
  prod-db-secret:
    description: 'production db secret file'

runs:
  using: "composite"
  steps:
    - name: Copy Oauth and S3 key
      env:
        OAUTH_SECRET: ${{ inputs.oauth-secret }}
        OAUTH_SECRET_DIR_FILE_NAME: application-oauth.yml
        S3_SECRET: ${{ inputs.s3-secret }}
        S3_SECRET_DIR_FILE_NAME: application-s3.yml
        FCM_SECRET: ${{ inputs.fcm-secret }}
        FCM_SECRET_DIR_FILE_NAME: application-fcm.yml
        FCM_KEY: ${{ inputs.fcm-key }}
        FCM_KEY_DIR: ${{ inputs.fcm-key-path }}
        FCM_KEY_FILE_NAME: ${{ inputs.fcm-key-file-name }}

        SECRET_DIR: src/main/resources
      shell: bash
      run: |
        echo $OAUTH_SECRET | base64 --decode > $SECRET_DIR/$OAUTH_SECRET_DIR_FILE_NAME
        echo $S3_SECRET | base64 --decode > $SECRET_DIR/$S3_SECRET_DIR_FILE_NAME
        echo $FCM_SECRET | base64 --decode > $SECRET_DIR/$FCM_SECRET_DIR_FILE_NAME
        mkdir $SECRET_DIR/$FCM_KEY_DIR
        echo $FCM_KEY | base64 --decode > $SECRET_DIR/$FCM_KEY_DIR/$FCM_KEY_FILE_NAME

    - name: Copy Dev DB Secrets
      if: inputs.profile == 'dev'
      env:
        DEV_DB_SECRET: ${{ inputs.dev-db-secret }}
        DEV_DB_DIR_FILE_NAME: application-dev-db.yml
        SECRET_DIR: src/main/resources
      shell: bash
      run: echo $DEV_DB_SECRET | base64 --decode > $SECRET_DIR/$DEV_DB_DIR_FILE_NAME

    - name: Copy Prod DB Secrets
      if: inputs.profile == 'prod'
      env:
        PROD_DB_SECRET: ${{ inputs.prod-db-secret }}
        PROD_DB_SECRET_DIR: src/main/resources
        PROD_DB_DIR_FILE_NAME: application-prod-db.yml
        SECRET_DIR: src/main/resources
      shell: bash
      run: echo $PROD_DB_SECRET | base64 --decode > $SECRET_DIR/$PROD_DB_DIR_FILE_NAME
