spring:
  datasource:
    url: jdbc:mysql://3.38.27.246:3306/join_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver