spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: 'jdbc:mysql://localhost:3306/join_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8'
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

api:
  prefix: /api/v1
