spring:
  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        # show formatted sql
        format_sql: true
        show_sql: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: 'jdbc:mysql://localhost:3306/join_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8'
    username: root
    password: password

api:
  prefix: /api/v1
